name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/freeshardbase/cicd-image:1.0.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build store data
        run: python3 build_store_data.py

      - name: Upload to Azure Blob Storage
        env:
          AZ_STORAGE_SAS_TOKEN: ${{ secrets.AZ_STORAGE_SAS_TOKEN }}
        run: |
          az storage blob upload-batch \
            --destination "app-store/master/all_apps" \
            --source apps \
            --sas-token $AZ_STORAGE_SAS_TOKEN \
            --account-name storageaccountportab0da \
            --overwrite
